language: node_js
node_js:
  - "8"
install:
  - npm install
script:
  - npm test
  - rm -f -R node_modules
  - git diff .
  - npm version patch

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
after_deploy:
  - git push origin master
